import React, { useEffect, useState } from 'react';
import { api } from '../../api/client';

type Entry = { id: string; amount: number; actual: number | null; state: string; created_at: string; note?: string; admin_id?: number; refunded?: number; context: { userId?: number; tokenId?: number; model?: string; operation?: string; contentId?: number } };
const labels: Record<string,string> = { reserved:'处理中', review:'待核对', settled:'已结算', refunded:'已退款' };
export default function BillingReviewPage() {
  const [items,setItems]=useState<Entry[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[state,setState]=useState('pending');
  const [selected,setSelected]=useState<Entry|null>(null),[actual,setActual]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{setBusy(true);setError('');try {const data=await api.get<{items:Entry[];total:number}>(`/admin/billing-reservations?page=${page}&state=${state}`);setItems(data.items);setTotal(data.total);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  useEffect(()=>{void load();},[page,state]);
  const resolve=async()=>{if(!selected)return;setBusy(true);setError('');try {await api.post(`/admin/billing-reservations/${selected.id}/resolve`,{actual:Number(actual),note});setSelected(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="p-5 md:p-8 space-y-5">
    <div><h1 className="text-xl font-bold">异常账单核对</h1><p className="text-sm opacity-70 mt-2">先核对上游任务结果与用量，再填写实收金额。差额将退回原扣款来源，实收为 0 时全额退款。</p></div>
    <div className="flex gap-3 items-center"><select aria-label="账单范围" value={state} onChange={e=>{setState(e.target.value);setPage(1);}} className="border rounded-lg p-2"><option value="pending">待处理</option><option value="all">全部记录</option></select><button className="border rounded-lg px-4 py-2" disabled={busy} onClick={()=>void load()}>刷新</button><span className="text-sm">共 {total} 条</span></div>
    {error&&<p role="alert" className="text-red-700">{error}</p>}
    <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm text-left"><thead><tr className="border-b"><th className="p-3">任务 / 用户</th><th>预扣 / 实收</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b"><td className="p-3"><div>{item.context.model||item.context.operation||'生成请求'} · 用户 {item.context.userId??'—'}</div><div className="text-xs opacity-60 mt-1">{item.created_at} UTC</div><div className="text-xs break-all opacity-60">{item.id}</div>{item.note&&<div className="mt-1">核对：{item.note}（管理员 {item.admin_id}）</div>}</td><td>¥{item.amount} / {item.actual===null?'待核对':`¥${item.actual}`}</td><td>{labels[item.state]}</td><td className="pr-3"><button disabled={item.state!=='review'||busy} className="border rounded-lg px-3 py-2 disabled:opacity-40" onClick={()=>{setSelected(item);setActual('');setNote('');}}>核对处理</button></td></tr>)}</tbody></table>{!items.length&&<p className="p-8 text-center">{busy?'正在加载…':'暂无账单'}</p>}</div>
    <div className="flex gap-4"><button disabled={page===1||busy} onClick={()=>setPage(page-1)}>上一页</button><span>{page}</span><button disabled={page*30>=total||busy} onClick={()=>setPage(page+1)}>下一页</button></div>
    <p className="text-xs opacity-60">超过 24 小时的未结算预扣会列入待核对，不会因超时自动退款。旧视频账单继续沿用原任务退款机制。</p>
    {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-5"><section role="dialog" aria-modal="true" aria-label="核对账单" className="bg-[#f6f3ea] text-[#26352b] rounded-2xl p-6 w-full max-w-lg space-y-4"><h2 className="font-bold text-lg">核对账单</h2><p>原预扣 ¥{selected.amount}。提交后不可重复结算。</p><label className="block">确认实收金额<input autoFocus type="number" min="0" max={selected.amount} step="0.000001" value={actual} onChange={e=>setActual(e.target.value)} className="block w-full border rounded-lg p-2 mt-1"/></label><label className="block">上游核对依据<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="填写任务编号、上游结果和确认费用" className="block w-full border rounded-lg p-2 mt-1" maxLength={2000}/></label><p>将退回 ¥{Math.max(0,selected.amount-Number(actual||0)).toFixed(6)}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex gap-3 justify-end"><button disabled={busy} onClick={()=>setSelected(null)}>取消</button><button className="bg-[#53684c] text-white px-4 py-2 rounded-lg" disabled={busy||!actual.trim()||!Number.isFinite(Number(actual))||Number(actual)<0||Number(actual)>selected.amount||note.trim().length<6} onClick={()=>void resolve()}>{busy?'处理中…':'确认结算并退回差额'}</button></div></section></div>}
  </div>;
}
