import { useRef, useState } from 'react';
import { Folder, Search, Plus, List, LayoutGrid, X, ArrowLeft, Upload, SlidersHorizontal } from 'lucide-react';
import { assetFolder, DEFAULT_ASSET_FOLDERS, type CanvasDocument, type CanvasNode } from './model';
import { connectionError } from './videoInputs';
type Props={document:CanvasDocument;projects:CanvasDocument[];selected?:CanvasNode;onClose:()=>void;onFocus:(n:CanvasNode)=>void;onReuse:(p:CanvasDocument,n:CanvasNode)=>void;onReference:(p:CanvasDocument,n:CanvasNode)=>void;onMove:(id:string,folder:string)=>void;onCreateFolder:(name:string)=>void;onUpload:(files:File[],folder?:string)=>void;onDownload:(n:CanvasNode)=>void};
export default function ProjectLibrary({document,projects,selected,onClose,onFocus,onReuse,onReference,onMove,onCreateFolder,onUpload,onDownload}:Props){
  const [scope,setScope]=useState('local'),[folder,setFolder]=useState<string|null>(null),[query,setQuery]=useState(''),[grid,setGrid]=useState(false),[filter,setFilter]=useState('all'),[filters,setFilters]=useState(false),[adding,setAdding]=useState(false),[name,setName]=useState(''),[sort,setSort]=useState(false);
  const input=useRef<HTMLInputElement>(null);
  const source=scope==='local'?[document]:projects.filter(p=>p.id!==document.id);
  const entries=source.flatMap(p=>p.nodes.map(n=>({p,n}))).filter(({p,n})=>(filter==='all'||n.kind===filter)&&(n.title+' '+n.text+' '+p.title).toLowerCase().includes(query.toLowerCase()));
  const folders=[...new Set([...DEFAULT_ASSET_FOLDERS,...source.flatMap(p=>p.assetFolders||[]),...source.flatMap(p=>p.nodes.map(assetFolder))])];
  if(sort)folders.sort((a,b)=>a.localeCompare(b,'zh-CN'));
  const items=entries.filter(({n})=>!folder||assetFolder(n)===folder);if(sort)items.sort((a,b)=>a.n.title.localeCompare(b.n.title,'zh-CN'));
  const ready=(n:CanvasNode)=>n.job?.status!=='running'&&Boolean(n.src||(n.kind==='text'&&n.text.trim()));
  return <aside className="studio-library project-library" aria-label="项目素材库" data-canvas-ui>
    <header><h2>素材库</h2><div><button aria-label="网格视图" aria-pressed={grid} onClick={()=>setGrid(true)}><LayoutGrid size={15}/></button><button aria-label="列表视图" aria-pressed={!grid} onClick={()=>setGrid(false)}><List size={15}/></button><button aria-label="关闭素材列表" onClick={onClose}><X size={16}/></button></div></header>
    <nav aria-label="素材项目范围">{[['local','本项目'],['cross','跨项目']].map(([id,label])=><button key={id} aria-pressed={scope===id} onClick={()=>{setScope(id);setFolder(null);setAdding(false);}}>{label}</button>)}</nav>
    <div className="project-library-search"><label><Search size={14}/><input aria-label="搜索画布素材" placeholder="搜索素材" value={query} onChange={e=>setQuery(e.target.value)}/></label><button aria-label="筛选素材类型" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={15}/></button>{scope==='local'&&<button aria-label="新建素材文件夹" aria-expanded={adding} onClick={()=>setAdding(!adding)}><Plus size={17}/></button>}</div>
    {filters&&<select aria-label="素材类型筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部类型</option><option value="image">图片</option><option value="video">视频</option><option value="audio">音频</option><option value="text">文字</option></select>}
    {adding&&<form onSubmit={e=>{e.preventDefault();const value=name.trim().slice(0,40);if(!value)return;onCreateFolder(value);setFolder(value);setName('');setAdding(false);}}><input autoFocus aria-label="文件夹名称" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="文件夹名称"/><button type="submit" disabled={!name.trim()}>创建</button></form>}
    <div className="project-library-path">{folder?<button onClick={()=>setFolder(null)}><ArrowLeft size={13}/>{folder}</button>:<strong>{query||filter!=='all'?'搜索结果':'全部'}</strong>}<button aria-label="按名称排序" aria-pressed={sort} onClick={()=>setSort(!sort)}>A↓Z</button></div>
    <div className={'project-library-content'+(grid?' is-grid':'')}>
      {!folder&&!query&&filter==='all'?folders.map(f=><button className="project-library-folder" key={f} onClick={()=>setFolder(f)}><Folder size={28}/><strong>{f}</strong><small>{entries.filter(({n})=>assetFolder(n)===f).length}</small></button>):<>{items.map(({p,n})=><article key={p.id+':'+n.id} className={selected?.id===n.id&&p.id===document.id?'selected':''}><button className="project-library-asset" onClick={()=>p.id===document.id?onFocus(n):onReuse(p,n)} title={p.id===document.id?'定位画布节点':'复制到当前画布'}>{n.kind==='image'&&n.src?<img src={n.src} alt=""/>:<span className="project-library-kind">{n.kind==='text'?'文':n.kind==='video'?'▶':n.kind==='audio'?'♫':'▧'}</span>}<span><strong>{n.title}</strong><small>{scope==='cross'?p.title:ready(n)?'可用素材':n.job?.status==='running'?'生成中':'待添加内容'}</small></span></button><div className="project-library-actions"><button disabled={!ready(n)||!selected||Boolean(connectionError(n,selected))||n.id===selected.id} onClick={()=>onReference(p,n)} title={selected?'引用到 '+selected.title:'请先选中生成节点'}>引用</button>{n.src&&<button onClick={()=>onDownload(n)}>下载</button>}{p.id===document.id&&<select aria-label={'移动素材 '+n.title} value={assetFolder(n)} onChange={e=>onMove(n.id,e.target.value)} disabled={n.job?.status==='running'}>{folders.map(f=><option key={f} value={f}>{f}</option>)}</select>}</div></article>)}{!items.length&&<p>暂无符合条件的素材</p>}</>}
    </div>
    {scope==='local'&&<footer><button onClick={()=>input.current?.click()}><Upload size={14}/>上传到{folder||'素材库'}</button><small>选中生成节点后，可引用素材</small></footer>}
    <input ref={input} type="file" multiple hidden aria-label="上传到素材文件夹" accept="image/*,video/mp4,video/webm,audio/*" onChange={e=>{onUpload(Array.from(e.target.files||[]),folder||undefined);e.target.value='';}}/>
  </aside>;
}
